{
  config,
  pkgs,
  lib,
  inputs,
  ...
}: let
  cfg = config.desktop.hyprland-configs;
  hyprsunsetPkg = inputs.hyprsunset.packages.${pkgs.stdenv.hostPlatform.system}.hyprsunset;

  # hl.monitor / hl.workspace_rule calls rendered from the options below.
  # `scale` is emitted bare because Lua wants a number there; everything else
  # is a quoted string, and `default` is only emitted when it is actually set.
  monitorLines =
    lib.concatMapStringsSep "\n"
    (m: ''hl.monitor({ output = "${m.output}", mode = "${m.mode}", position = "${m.position}", scale = ${toString m.scale} })'')
    cfg.monitors;

  workspaceLines =
    lib.concatMapStringsSep "\n"
    (w: ''hl.workspace_rule({ workspace = "${toString w.id}", monitor = "${w.monitor}"${lib.optionalString w.default ", default = true"} })'')
    cfg.workspaces;

  hostLua = ''
    -- Generated by modules/home-manager/packages/hyprland-configs.nix -- do not edit.
    ${monitorLines}

    ${workspaceLines}
  '';

  # Hyprland plugins. How to add one:
  #   1. Take it from pkgs.hyprlandPlugins (nixpkgs). Home-manager uses the
  #      global pkgs (useGlobalPkgs), so these are built against the exact
  #      pkgs.hyprland that programs.hyprland runs -- Hyprland refuses a
  #      plugin built for any other version/commit.
  #   2. Do NOT (re-)add a plugin flake input such as `hyprland-plugins` or
  #      `hypr-dynamic-cursors` (both were removed): they follow the upstream
  #      `hyprland` flake, not the nixpkgs hyprland we actually run, so their
  #      builds are ABI-mismatched.
  #   3. Test-build it first -- nixpkgs lags Hyprland's internal API, and a
  #      plugin can be in nixpkgs yet fail to compile (hyprsplit, hyprspace,
  #      imgborders and hyprgrass all failed against 0.56.2):
  #        nix build --impure --expr '(builtins.getFlake "/etc/nixos").inputs.nixpkgs.legacyPackages.x86_64-linux.hyprlandPlugins.<name>'
  #   4. Add it to the list below, then configure it in hyprland.lua inside an
  #      `if hl.plugin.<namespace> then ... end` guard (see the PLUGINS section
  #      there for why the guard is required).
  # Every package here installs lib/lib<pname>.so.
  plugins = with pkgs.hyprlandPlugins; [
    hyprtasking
    hypr-dynamic-cursors
    hyprfocus
    hypr-darkwindow
    hyprbars
  ];

  # hl.plugin.load only registers the path; Hyprland loads the plugins after
  # the config has run and then re-evaluates the config once.
  pluginsLua = ''
    -- Generated by modules/home-manager/packages/hyprland-configs.nix -- do not edit.
    ${lib.concatMapStringsSep "\n" (p: ''hl.plugin.load("${p}/lib/lib${p.pname}.so")'') plugins}
  '';
in {
  options.desktop.hyprland-configs = {
    enable = lib.mkEnableOption "hyprland configs";

    monitors = lib.mkOption {
      type = lib.types.listOf (lib.types.submodule {
        options = {
          output = lib.mkOption {
            type = lib.types.str;
            example = "DP-3";
            description = "Connector name of the output, as reported by `hyprctl monitors`.";
          };

          mode = lib.mkOption {
            type = lib.types.str;
            default = "preferred";
            example = "2560x1440@144";
            description = "Resolution and refresh rate for this output.";
          };

          position = lib.mkOption {
            type = lib.types.str;
            default = "auto";
            example = "2560x0";
            description = "Position of this output in the global layout.";
          };

          scale = lib.mkOption {
            type = lib.types.number;
            default = 1;
            example = 1.25;
            description = "Scale factor for this output.";
          };
        };
      });
      default = [];
      description = ''
        Host-specific monitor layout, rendered into `hypr/host.lua` as
        `hl.monitor` calls.
      '';
    };

    workspaces = lib.mkOption {
      type = lib.types.listOf (lib.types.submodule {
        options = {
          id = lib.mkOption {
            type = lib.types.int;
            example = 1;
            description = "Workspace number the rule applies to.";
          };

          monitor = lib.mkOption {
            type = lib.types.str;
            example = "DP-3";
            description = "Output this workspace is bound to.";
          };

          default = lib.mkOption {
            type = lib.types.bool;
            default = false;
            description = "Whether this is the workspace its monitor opens on.";
          };

          showInBar = lib.mkOption {
            type = lib.types.bool;
            default = true;
            description = ''
              Whether the quickshell bar draws a button for this workspace.
              Turn it off for workspaces the keybinds cannot reach -- the rule
              still applies, the bar just does not advertise it.
            '';
          };
        };
      });
      default = [];
      description = ''
        Host-specific workspace-to-monitor rules, rendered into
        `hypr/host.lua` as `hl.workspace_rule` calls.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # Hyprland 0.56 introduced a Lua-first config model and looks for
    # hyprland.lua in ~/.config/hypr/ first. This is our real, hand-migrated
    # config, and the only one -- the old hyprlang programs.hyprland.settings
    # in modules/nixos/desktop/hyprland.nix has been deleted, so nothing
    # generates an /etc/xdg/hypr/hyprland.conf to fall back to. If
    # ~/.config/hypr has neither a .lua nor a .conf, Hyprland
    # silently drops a brand-new example config instead -- that's what broke
    # kb_layout and the monitor order after the last update.
    xdg.configFile."hypr/hyprland.lua".source = ./hyprland.lua;

    # hyprland.lua above is installed verbatim and therefore has to stay
    # host-agnostic, but the monitor layout and the workspace-to-monitor rules
    # are per-host. They are declared as options on this module and generated
    # into a separate host.lua, which hyprland.lua pulls in with `dofile` near
    # the top -- the chunk runs in the same environment, so the `hl` global is
    # already in scope there. Anything genuinely wotan-specific belongs in
    # hosts/wotan/home.nix, not in hyprland.lua.
    xdg.configFile."hypr/host.lua".text = hostLua;

    # Store paths of the plugin .so files; loaded by hyprland.lua the same way
    # as host.lua. The plugin list and how to add to it are at the top of
    # this file.
    xdg.configFile."hypr/plugins.lua".text = pluginsLua;

    # wlogout layout ($mod+Q menu). Copied from the package default MINUS the
    # Hibernate button: hibernation is disabled by security.protectKernelImage
    # (nohibernate kernel param), so the button was a silent no-op. Styling and
    # icons fall back to the packaged style.css.
    xdg.configFile."wlogout/layout".text = ''
      {
          "label" : "lock",
          "action" : "loginctl lock-session",
          "text" : "Lock",
          "keybind" : "l"
      }
      {
          "label" : "suspend",
          "action" : "systemctl suspend",
          "text" : "Suspend",
          "keybind" : "u"
      }
      {
          "label" : "shutdown",
          "action" : "systemctl poweroff",
          "text" : "Shutdown",
          "keybind" : "s"
      }
    '';

    xdg.configFile."hypr/hyprsunset.conf".text = ''
      # Maximum gamma value (percentage, 100 = 1.0x)
      max-gamma = 100

      # Evening profile - warm color temperature at night
      profile {
          time = 20:00
          temperature = 4500
          gamma = 1.0
          identity = 0
      }

      # Night profile - warm color temperature at night
      profile {
          time = 22:00
          temperature = 3500
          gamma = 1.0
          identity = 0
      }

      # Morning profile - return to daylight temperature
      profile {
          time = 08:00
          temperature = 5500
          gamma = 1.0
          identity = 0
      }
    '';

    # hyprsunset daemon. The package ships a systemd user unit, but it is only
    # linked (never enabled/WantedBy the session), so nothing started it and the
    # `.hyprsunset.sock` was never created -> `hyprctl hyprsunset ...` (the mod+H
    # keybind and the quickshell SysInfoWidget) failed with a socket error.
    # Managing it here wires it into graphical-session.target and applies the
    # time-based profiles from hyprsunset.conf on login.
    systemd.user.services.hyprsunset = {
      Unit = {
        Description = "hyprsunset blue-light filter";
        Documentation = "https://wiki.hyprland.org/Hypr-Ecosystem/hyprsunset/";
        PartOf = ["graphical-session.target"];
        After = ["graphical-session.target"];
        ConditionEnvironment = "WAYLAND_DISPLAY";
        # hyprsunset 0.3.3 asserts-and-crashes when the compositor connection
        # drops (e.g. DPMS off from hypridle). Disable the restart rate limiter
        # so it self-heals instead of hitting start-limit-hit and staying dead.
        StartLimitIntervalSec = 0;
      };
      Service = {
        Type = "simple";
        ExecStart = "${hyprsunsetPkg}/bin/hyprsunset";
        Restart = "on-failure";
        RestartSec = 2;
      };
      Install.WantedBy = ["graphical-session.target"];
    };

    # Clipboard history store (wl-paste --watch cliphist store); picker is the
    # SUPER+SHIFT+V bind in hyprland.lua.
    services.cliphist.enable = true;

    xdg.configFile."hypr/hypridle.conf".text = ''
      general {
          # Hyprland 0.56 evaluates `hyprctl dispatch` as Lua, so the old
          # hyprlang "dpms on" string is a syntax error -- use hl.dsp.dpms.
          # The field MUST be `action`: hl.dsp.dpms parses the table with
          # tableToggleAction(field = "action"), and an unrecognized field
          # (e.g. `state`) SILENTLY falls back to TOGGLE, so every command
          # below flipped the dpms state instead of setting it -- monitors
          # ended up off while Hyprland reported dpmsStatus=true and key
          # presses stopped waking them.
          lock_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'; pidof hyprlock || hyprlock       # turn on display so screenshot isn't blank, avoid starting multiple hyprlock instances
          before_sleep_cmd = loginctl lock-session    # lock before suspend
          after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'  # turn on display after sleep
          ignore_dbus_inhibit = false                 # respect idle-inhibit requests (e.g., from firefox, steam)
          ignore_systemd_inhibit = false              # respect systemd-inhibit --what=idle inhibitors
      }

      # Screen dimming after 10 minutes
      listener {
          timeout = 600                               # 10 minutes
          on-timeout = if [ "$(playerctl status 2>/dev/null)" != "Playing" ]; then brightnessctl -s set 10; fi        # dim screen
          on-resume = brightnessctl -r                # restore brightness
      }

      # Screen off after 15 minutes
      listener {
          timeout = 900                               # 15 minutes
          on-timeout = if [ "$(playerctl status 2>/dev/null)" != "Playing" ]; then hyprctl dispatch 'hl.dsp.dpms({ action = "off" })'; fi      # turn off screen
          on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'        # turn on screen
      }

      # Lock screen after 20 minutes
      listener {
          timeout = 1200                              # 20 minutes
          on-timeout = if [ "$(playerctl status 2>/dev/null)" != "Playing" ]; then loginctl lock-session; fi          # lock screen
      }

      # Suspend after 60 minutes
      listener {
          timeout = 3600                              # 60 minutes
          on-timeout = if [ "$(playerctl status 2>/dev/null)" != "Playing" ]; then systemctl suspend; fi              # suspend system
      }
    '';

    xdg.configFile."hypr/hyprlock.conf".text = ''
      # Matches the bar and the launcher. "Monospace" is whatever fontconfig
      # decides that means, which is not Berkeley Mono.
      $font = Berkeley Mono

      general {
          hide_cursor = false
      }

      animations {
          enabled = true
          bezier = linear, 1, 1, 0, 0
          animation = fadeIn, 1, 5, linear
          animation = fadeOut, 1, 5, linear
          animation = inputFieldDots, 1, 2, linear
      }

      background {
          monitor =
          path = screenshot
          blur_passes = 3
      }

      input-field {
          monitor =
          size = 20%, 5%
          outline_thickness = 3
          inner_color = rgba(0, 0, 0, 0.0)

          outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
          check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
          fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

          font_color = rgb(207, 214, 244)   # Theme.text
          fade_on_empty = false
          rounding = 15

          font_family = $font
          placeholder_text = Input password...
          fail_text = $PAMFAIL

          dots_spacing = 0.3

          position = 0, -20
          halign = center
          valign = center
      }

      label {
          monitor =
          text = $TIME
          font_size = 90
          font_family = $font

          position = -30, 0
          halign = right
          valign = top
      }

      label {
          monitor =
          text = cmd[update:60000] date +"%A, %d %B %Y"
          font_size = 25
          font_family = $font

          position = -30, -150
          halign = right
          valign = top
      }


    '';

    services.dunst = {
      # Only when it owns the bus name -- see desktop.notifications.backend.
      enable = config.desktop.notifications.backend == "dunst";
      package = pkgs.dunst;
      settings = {
        global = {
          monitor = 0;
          follow = "keyboard";
          # Replaced deprecated geometry setting with width, height, origin, offset
          width = 460;
          # Max height, not fixed height. At the old 100px a two-line body no
          # longer fit once the font went to 13px, so word_wrap silently gave
          # way to mid-sentence ellipsis.
          height = "(0, 220)";
          origin = "top-right";
          offset = "(32, 48)";
          transparency = 0;
          separator_height = 2;
          padding = 18;
          horizontal_padding = 24;
          notification_limit = 2;
          # Berkeley Mono, not FiraCode Nerd Font: that family is not installed
          # on this host, so it resolved to Noto Sans and every notification
          # rendered in a different typeface to the rest of the desktop.
          # Check with `fc-match "<name>"` before changing.
          font = "Berkeley Mono 13";
          line_height = 0;
          format = "<b>%s</b>\\n%b";
          alignment = "left";
          icon_position = "left";
          min_icon_size = 48;
          max_icon_size = 80;
          frame_width = 2;
          corner_radius = 12;
          word_wrap = true;
          sort = true;
          indicate_hidden = true;
          show_indicators = false;
          idle_threshold = 120;
          enable_recursive_icon_lookup = true;
          stack_duplicates = true;
          mouse_left_click = "close_current";
          mouse_middle_click = "do_action";
          mouse_right_click = "close_all";
        };

        # Colours are Theme.qml's (see quickshell/Theme.qml) so notifications
        # match the bar and the launcher. The frame carries the urgency: muted
        # for low, accent for normal, crit for critical -- previously low was
        # accent-cyan and normal was a green found nowhere else in the palette,
        # which made a routine notification look more alarming than a low one.
        urgency_low = {
          background = "#1e1e28";
          foreground = "#a6adc8";
          frame_color = "#6c7086";
          timeout = 4;
        };

        urgency_normal = {
          background = "#1e1e28";
          foreground = "#cfd6f4";
          frame_color = "#33ccff";
          timeout = 6;
        };

        urgency_critical = {
          background = "#1e1e28";
          foreground = "#cfd6f4";
          frame_color = "#ff6b6b";
          timeout = 0;
        };
      };
    };
  };
}
