{
  config,
  pkgs,
  lib,
  inputs,
  ...
}: let
  cfg = config.desktop.quickshell;
  quickshell = inputs.quickshell.packages.${pkgs.stdenv.hostPlatform.system}.default;

  # Audio switch script using rofi
  audio-switch = pkgs.writeShellScriptBin "audio-switch" ''
    set -euo pipefail

    # List all audio sinks
    sinks=$(${pkgs.wireplumber}/bin/wpctl status | sed -n '/Audio/,/Video/{/Sinks:/,/Sources:/p}' | grep -E '^\s*[│├└].*[0-9]+\.' | sed 's/[│├└]//g; s/^\s*//')

    if [ -z "$sinks" ]; then
      ${pkgs.libnotify}/bin/notify-send "Audio" "No audio sinks found"
      exit 1
    fi

    # Show rofi menu
    selected=$(echo "$sinks" | ${pkgs.rofi}/bin/rofi -dmenu -i -p "󰓃 Audio Output" -theme-str 'window {width: 450px;}')

    if [ -n "$selected" ]; then
      sink_id=$(echo "$selected" | grep -oE '[0-9]+\.' | head -1 | tr -d '.')
      if [ -n "$sink_id" ]; then
        ${pkgs.wireplumber}/bin/wpctl set-default "$sink_id"
        sink_name=$(echo "$selected" | sed 's/^[* ]*[0-9]*\. //' | cut -d'[' -f1 | xargs)
        ${pkgs.libnotify}/bin/notify-send "󰓃 Audio" "Switched to: $sink_name"
      fi
    fi
  '';

  # Runtime dependencies for shell scripts and widgets. The resource widgets
  # shell out on a timer, so everything they call has to be on the service's
  # PATH -- a missing binary shows up as a permanently blank readout, not an
  # error.
  dependencies = with pkgs; [
    bash
    coreutils # cat, df -- disk and hwmon readouts
    gawk # /proc/stat and free parsing
    gnugrep
    procps # free
    curl # for weather widget
    wireplumber # for wpctl audio control
    libnotify # for notify-send
    rofi # for audio device selection menu
  ];

  # The bar has to show the same workspaces on a monitor that Hyprland actually
  # binds to it, so both are rendered from the single declaration in
  # desktop.hyprland-configs.workspaces. Keying off Hyprland's numeric monitor
  # id instead would be wrong: those ids are handed out in the order outputs get
  # enabled, so they swap between sessions (and on re-plug/DPMS) while the
  # workspace rules stay pinned to the output *name*.
  hyprWorkspaces =
    lib.filter (w: w.showInBar)
    config.desktop.hyprland-configs.workspaces;
  sortedIds = ws: lib.sort (a: b: a < b) (lib.unique (map (w: w.id) ws));
  idList = ws: lib.concatMapStringsSep ", " toString (sortedIds ws);

  monitorEntries =
    lib.concatStringsSep ",\n    "
    (lib.mapAttrsToList (output: ws: ''"${output}": [${idList ws}]'')
      (lib.groupBy (w: w.monitor) hyprWorkspaces));

  # Monitor owning the lowest workspace number -- the one widgets that should
  # only appear once (git status) attach to.
  primaryOutput =
    if hyprWorkspaces == []
    then ""
    else (lib.head (lib.sort (a: b: a.id < b.id) hyprWorkspaces)).monitor;

  workspaceLayoutQml = ''
    pragma Singleton

    // Generated by modules/home-manager/packages/quickshell.nix -- do not edit.
    import QtQuick

    QtObject {
      // Output name, as reported by `hyprctl monitors`, -> workspaces shown there.
      readonly property var byMonitor: ({
        ${monitorEntries}
      })

      // Used for outputs with no rule of their own (hotplugged screens).
      readonly property var fallback: [${idList hyprWorkspaces}]

      readonly property string primary: "${primaryOutput}"
    }
  '';

  # The generated layout ships as its own QML module on the import path rather
  # than as a file inside the config directory. That keeps the config directory
  # 100% hand-written, which is what lets `liveReload` point it straight at the
  # source tree -- a directory that mixes tracked sources with a Nix-generated
  # file cannot be symlinked anywhere useful.
  generatedQml = pkgs.runCommand "quickshell-generated-qml" {} ''
    mkdir -p $out/Generated
    cat > $out/Generated/qmldir <<'EOF'
    module Generated
    singleton WorkspaceLayout 1.0 WorkspaceLayout.qml
    EOF
    cp ${pkgs.writeText "WorkspaceLayout.qml" workspaceLayoutQml} $out/Generated/WorkspaceLayout.qml
  '';

  # QML import paths for Qt6
  qmlImportPath = lib.concatStringsSep ":" [
    "${quickshell}/lib/qt-6/qml"
    "${pkgs.kdePackages.qtdeclarative}/lib/qt-6/qml"
    "${generatedQml}"
  ];

  quickshellConfig = pkgs.runCommand "quickshell-config" {} ''
    mkdir -p $out
    cp ${./quickshell}/*.qml $out/
  '';
in {
  imports = [
    ../services/hyprland-session.nix
    ./hyprland-configs.nix
  ];

  options.desktop.quickshell = {
    enable = lib.mkEnableOption "quickshell custom widgets";

    liveReload = lib.mkEnableOption ''
      pointing ~/.config/quickshell straight at the source tree instead of a
      read-only copy in the Nix store.

      Quickshell watches its config directory and reloads on any change, so
      with this on, editing a .qml file under sourcePath updates the bar
      immediately -- including brand-new widget files -- with no rebuild. The
      cost is that the running shell no longer matches what the flake builds
      until you rebuild, so leave it off unless you are actively working on
      the widgets
    '';

    sourcePath = lib.mkOption {
      type = lib.types.str;
      default = "/etc/nixos/modules/home-manager/packages/quickshell";
      description = ''
        Absolute path to the QML sources, used only when liveReload is on.
        Must be a real path on the running system, not a store path.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [
      quickshell
      audio-switch # Rofi-based audio output switcher
      pkgs.pwvucontrol # Modern PipeWire volume control GUI (bar: right-click volume)
      pkgs.pulsemixer # TUI audio mixer
    ];

    # Set QML import path for proper module resolution
    home.sessionVariables.QML2_IMPORT_PATH = qmlImportPath;

    # Either a read-only copy of the QML in the store (the default), or a
    # symlink to the working tree for live editing. The generated
    # WorkspaceLayout singleton reaches both through QML2_IMPORT_PATH.
    xdg.configFile."quickshell".source =
      if cfg.liveReload
      then config.lib.file.mkOutOfStoreSymlink cfg.sourcePath
      else quickshellConfig;

    # Systemd service for Quickshell
    systemd.user.services.quickshell = {
      Unit = {
        Description = "Quickshell custom widgets";
        PartOf = ["hyprland-session.target"];
        After = ["hyprland-session.target"];
      };

      Service = {
        Environment = [
          "PATH=/run/wrappers/bin:${lib.makeBinPath dependencies}:/run/current-system/sw/bin:${config.home.profileDirectory}/bin"
          "QML2_IMPORT_PATH=${qmlImportPath}"
          # Overrides the session-wide QT_QPA_PLATFORMTHEME=kvantum for this
          # service only. Kvantum is a widget *style* and gives Qt no icon
          # theme, so QIcon resolves nothing and system tray icons render as
          # the magenta "missing image" placeholder. The gtk3 platform theme
          # reads gtk-icon-theme-name out of ~/.config/gtk-3.0/settings.ini and
          # makes the whole icon theme available. Quickshell draws its own QML
          # UI and uses no Qt widget styling, so nothing is lost by not using
          # Kvantum here. Needs the correctly-cased theme name in gtk.nix --
          # with either half missing, icon lookup still fails.
          "QT_QPA_PLATFORMTHEME=gtk3"
        ];
        ExecStart = lib.getExe quickshell;
        Restart = "on-failure";
        RestartSec = 3;
        # Only kill quickshell itself on stop/restart, not apps launched from
        # the dock. Dock apps (Quickshell.execDetached) inherit this service's
        # cgroup; the default KillMode=control-group would take them down with
        # a `systemctl restart`.
        KillMode = "process";
      };

      Install = {
        WantedBy = ["hyprland-session.target"];
      };
    };
  };
}
