-- Hyprland Lua config, migrated from the hyprlang settings that used to live
-- in modules/desktop/hyprland.nix and hosts/wotan/desktop-config.nix
-- (Hyprland 0.56 moved to Lua as the config format it looks for first).
--
-- Dispatcher/field names below were verified against the Hyprland source at
-- the pinned commit (src/config/lua/bindings/LuaBindingsDispatchers.cpp and
-- LuaBindingsConfigRules.cpp), not guessed from docs -- the wiki is
-- JS-rendered and wasn't fetchable.
--
-- This file is the sole Hyprland config: there is no hyprlang fallback any
-- more, nothing generates /etc/xdg/hypr/hyprland.conf and there is no
-- ~/.config/hypr/hyprland.conf. That makes parse errors here loud in effect
-- but silent in the log: if this file fails to load, Hyprland just drops a
-- brand-new example config and comes up with it, which is what previously
-- lost kb_layout and the monitor order.

------------------
---- MONITORS ----
------------------

-- host.lua is generated by modules/home/packages/hyprland-configs.nix
-- from the desktop.hyprland-configs.monitors and
-- desktop.hyprland-configs.workspaces options. It holds the monitor layout
-- and the workspace-to-monitor rules, which are per-host and must not be
-- hardcoded in this shared file. `hl` and its functions stay visible inside
-- the loaded chunk.
--
-- Loaded via loadfile rather than dofile on purpose: dofile raises on a
-- missing file, which would abort this whole config and land us on Hyprland's
-- example config -- the exact silent breakage described above. Degrading to
-- "monitors on autodetect" instead leaves a screen you can actually read the
-- notification on.
local hostPath = (os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")) .. "/hypr/host.lua"
local hostChunk, hostErr = loadfile(hostPath)
if hostChunk then
    hostChunk()
else
    hl.notification.create({
        text = "hyprland.lua: could not load " .. hostPath .. " -- monitors and workspace rules are NOT applied (" .. tostring(hostErr) .. ")",
        time = 15000,
    })
end

-- plugins.lua is generated the same way: hl.plugin.load calls with the
-- nix-store paths of the plugins listed (and explained, including how to add
-- one) in modules/home/packages/hyprland-configs.nix. Their
-- configuration is in the PLUGINS section at the end of this file.
local pluginsPath = (os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")) .. "/hypr/plugins.lua"
local pluginsChunk, pluginsErr = loadfile(pluginsPath)
if pluginsChunk then
    pluginsChunk()
else
    hl.notification.create({
        text = "hyprland.lua: could not load " .. pluginsPath .. " -- plugins are NOT loaded (" .. tostring(pluginsErr) .. ")",
        time = 15000,
    })
end

---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout = "de",
        follow_mouse = 1,
        numlock_by_default = true,
        sensitivity = 0,
        touchpad = {
            natural_scroll = false,
        },
    },
})

-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 20,
        border_size = 2,
        col = {
            active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
        layout = "dwindle",
        resize_on_border = false,
        -- Only windows with the `immediate` rule (games, see below) tear
        allow_tearing = true,
    },

    dwindle = {
        preserve_split = true,
    },

    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        focus_on_activate = true,
        -- VRR only for fullscreen windows: always-on VRR flickers on NVIDIA
        -- with a mostly static desktop. 2 = fullscreen (Lua rejects the name)
        vrr = 2,
    },

    decoration = {
        rounding = 10,
        dim_inactive = false,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = 0xee1a1a1a,
        },
        blur = {
            enabled = false,
        },
    },

    cursor = {
        no_hardware_cursors = 1,
    },
})

hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("snappy", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.0 } } })
hl.animation({ leaf = "windows", enabled = true, speed = 4, bezier = "easeOutQuint" })
hl.animation({ leaf = "fade", enabled = true, speed = 3, bezier = "easeOutQuint" })
hl.animation({ leaf = "border", enabled = true, speed = 6, bezier = "easeOutQuint" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 3, bezier = "snappy" })

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland")
    hl.exec_cmd("systemctl --user start hyprland-session.target")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("sleep 1 && next-wallpaper --transition-type random --transition-fps 60")
    -- hyprsunset runs via its systemd user service (hyprsunset.service), see
    -- modules/home/packages/hyprland-configs.nix for why.
    hl.exec_cmd("hypridle")
end)

---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER"

-- Application launcher
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("rofi -show drun -run-command 'bash -c \"{cmd}\"'"))

-- Window switcher. Same rofi, different mode -- lists open windows across both
-- monitors and every workspace, which is the one thing the bar cannot show.
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("rofi -show window"))

-- Terminal
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("kitty"))

-- Browser
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd("brave"))

-- File manager
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("thunar"))

-- Wallpaper
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("next-wallpaper"))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("previous-wallpaper"))

-- Screenshot (saves to ~/Pictures/hyprshot and copies to clipboard)
hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m region --freeze -o ~/Pictures/hyprshot"))
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd("hyprshot -m window -o ~/Pictures/hyprshot"))
hl.bind(mainMod .. " + SHIFT + Print", hl.dsp.exec_cmd("hyprshot -m output --freeze -o ~/Pictures/hyprshot"))
-- Region screenshot opened in satty for annotation (save/copy from satty)
hl.bind("CTRL + Print", hl.dsp.exec_cmd("hyprshot -m region --freeze --raw | satty --filename - --output-filename ~/Pictures/hyprshot/satty-%Y%m%d-%H%M%S.png --copy-command wl-copy"))

-- Color picker (copies hex to clipboard)
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("hyprpicker -a"))

-- Clipboard history (cliphist is fed by the home-manager cliphist service)
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd("cliphist list | rofi -dmenu -display-columns 2 -p clipboard | cliphist decode | wl-copy"))

-- Scratchpad: overlay workspace toggled over whatever is on screen
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("scratch"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:scratch" }))

-- Lockscreen
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))

-- Exit menu
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd("wlogout"))

-- Window controls
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.layout("togglesplit"))

-- Focus
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

-- Move/swap window within workspace; crosses to adjacent monitor only
-- when there is no window in that direction
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({ direction = "down" }))

-- Swap the two monitors' active workspaces; the workspace numbers stay on
-- their monitor. The workspace objects are swapped (swap_monitors), which
-- carries each dwindle tree across untouched, so every split keeps its
-- orientation and ratio. Moving the windows one by one instead re-inserts
-- them into the target workspace, and dwindle picks each new split from the
-- aspect ratio of the window it lands next to (preserve_split only guards
-- resizes), so a vertical stack could arrive side by side.
-- swap_monitors also strands the numbers (workspace 1 would sit on the right
-- monitor), so the two ids are traded back via a temporary id (change_id
-- refuses an id that is taken). change_id re-labels compositor-side without
-- an event quickshell handles, so the bar would count windows on their
-- pre-swap buttons; restarting the quickshell user service resyncs it.
local swapTempId = 9999
hl.bind(mainMod .. " + SHIFT + up", function()
    local here = hl.get_active_workspace()
    local other
    for _, m in ipairs(hl.get_monitors()) do
        if not m.focused then
            other = m.active_workspace
        end
    end
    -- Named/special workspaces have ids <= 0, which change_id cannot touch
    if not here or not other or here.id <= 0 or other.id <= 0 then
        return
    end
    local a, b = here.id, other.id
    hl.dispatch(hl.dsp.workspace.swap_monitors({ monitor1 = "current", monitor2 = "+1" }))
    hl.dispatch(hl.dsp.workspace.change_id({ workspace = a, id = swapTempId }))
    hl.dispatch(hl.dsp.workspace.change_id({ workspace = b, id = a }))
    hl.dispatch(hl.dsp.workspace.change_id({ workspace = swapTempId, id = b }))
    hl.dispatch(hl.dsp.exec_cmd("systemctl --user restart quickshell.service"))
end)

-- Push window to the previous/next monitor unconditionally (works for tiled
-- and fullscreen windows, e.g. moving a fullscreen video). The Lua
-- hl.window.move only resolves a monitor by name, numeric id or relative
-- offset -- hyprlang's directional `mon:l` selector has no equivalent here,
-- so "-1"/"+1" it is.
hl.bind(mainMod .. " + CTRL + left", hl.dsp.window.move({ monitor = "-1" }))
hl.bind(mainMod .. " + CTRL + right", hl.dsp.window.move({ monitor = "+1" }))
-- No Ctrl+Up/Down: there is no directional monitor selector in Lua, and on
-- this side-by-side two-monitor layout up/down were no-ops anyway.

-- Media keys (pass through to applications like Firefox)
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioStop", hl.dsp.exec_cmd("playerctl stop"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))

-- Volume keys (work on the lock screen, repeat when held; capped at 100%)
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

-- Hyprsunset temperature adjustment (+/- 500K)
hl.bind(mainMod .. " + H", hl.dsp.exec_cmd("hyprctl hyprsunset temperature +500"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("hyprctl hyprsunset temperature -500"))
hl.bind(mainMod .. " + SHIFT + H", hl.dsp.exec_cmd("pkill hyprsunset; hyprsunset -i"))

-- Window grouping (tabbed layout)
hl.bind(mainMod .. " + G", hl.dsp.group.toggle())
hl.bind(mainMod .. " + TAB", hl.dsp.group.next())
hl.bind(mainMod .. " + SHIFT + TAB", hl.dsp.group.prev())
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.window.move({ out_of_group = true }))

-- Audio output switching (rofi menu / pwvucontrol GUI)
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("audio-switch"))
hl.bind(mainMod .. " + SHIFT + A", hl.dsp.exec_cmd("pwvucontrol"))

-- Workspace bindings (number row: code:10-18 = 1-9). Deliberately no bind
-- for workspace 10: it is not needed. host.lua still binds it to the right
-- monitor, but the bar leaves it out (showInBar in hosts/wotan/home.nix).
for i = 0, 8 do
    local ws = i + 1
    hl.bind(mainMod .. " + code:1" .. i, hl.dsp.focus({ workspace = ws }))
    hl.bind(mainMod .. " + SHIFT + code:1" .. i, hl.dsp.window.move({ workspace = ws }))
end

-- Numpad workspace bindings (KP_1-KP_9)
-- Numpad layout: 7(79) 8(80) 9(81) / 4(83) 5(84) 6(85) / 1(87) 2(88) 3(89)
local numpadCodes = { 87, 88, 89, 83, 84, 85, 79, 80, 81 } -- KP_1 through KP_9
for i, code in ipairs(numpadCodes) do
    hl.bind(mainMod .. " + code:" .. code, hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + code:" .. code, hl.dsp.window.move({ workspace = i }))
end

-- Mouse bindings
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- Force Brave windows to open tiled (it sometimes requests floating)
hl.window_rule({
    name = "brave-tile",
    match = { class = "(?i)brave.*" },
    tile = true,
})

-- ueberzugpp (yazi image preview) must stay floating
hl.window_rule({
    name = "ueberzugpp",
    match = { class = "ueberzugpp" },
    no_focus = true,
    no_shadow = true,
    no_blur = true,
    border_size = 0,
    float = true,
    no_anim = true,
    pin = true,
    no_initial_focus = true,
})

-- Scratchpad doubles as a system dashboard: the first SUPER+S spawns btop and
-- nvtop side by side (dwindle splits the wide monitor horizontally); later
-- toggles just show/hide them. Which side each lands on follows the cursor
-- (dwindle splits toward it).
hl.workspace_rule({
    workspace = "special:scratch",
    on_created_empty = "kitty --class dashboard btop & sleep 0.3; kitty --class dashboard nvtop",
})

-- Red border on scratchpad (any special workspace) windows, so it is obvious
-- the overlay is up rather than a regular workspace
hl.window_rule({
    name = "scratchpad-border",
    match = { workspace = "s[true]" },
    border_color = "rgb(ff3333)",
})

-- Small utility / dialog windows float centered instead of splitting a tile
hl.window_rule({
    name = "float-utilities",
    match = { class = "(?i)(com\\.saivert\\.pwvucontrol|org\\.pulseaudio\\.pavucontrol|blueman-manager|nm-connection-editor|xdg-desktop-portal-gtk|org\\.gnome\\.Calculator)" },
    float = true,
    center = true,
})
hl.window_rule({
    name = "float-dialogs",
    match = { title = "(?i)^(open|save|choose|select).*(file|folder|files).*" },
    float = true,
    center = true,
})

-- Picture-in-Picture video stays on top across workspaces
hl.window_rule({
    name = "pip",
    match = { title = "(?i)^picture[- ]in[- ]picture$" },
    float = true,
    pin = true,
    keep_aspect_ratio = true,
})

-- Any fullscreen window (games, videos) blocks hypridle's dim/lock/suspend
hl.window_rule({
    name = "idle-inhibit-fullscreen",
    match = { class = ".*" },
    idle_inhibit = "fullscreen",
})

-- Games may tear (general.allow_tearing) for lowest input latency
hl.window_rule({
    name = "tearing-steam-games",
    match = { class = "steam_app_.*" },
    immediate = true,
})
hl.window_rule({
    name = "tearing-game-content",
    match = { content = "game" },
    immediate = true,
})

-- Fyrox sets no Wayland app ID, so match on the title. The editor's title
-- grows the scene name, hence initial_title; the game's title is fixed.
-- Both open on the first empty workspace.
hl.window_rule({
    name = "fyrox-game",
    match = { initial_title = "^(Fyrox Game)$" },
    workspace = "empty",
})
hl.window_rule({
    name = "fyrox-editor",
    match = { initial_title = "^(FyroxEd)" },
    workspace = "empty",
})

-----------------
---- PLUGINS ----
-----------------

-- The plugins are loaded by plugins.lua (top of this file); which plugins,
-- and how to add one, is documented in
-- modules/home/packages/hyprland-configs.nix. In short: take them
-- from pkgs.hyprlandPlugins, never from the `hyprland-plugins` flake input.
--
-- Every block below is guarded with `if hl.plugin.<namespace> then`.
-- hl.plugin.load only registers a path: Hyprland loads the plugins after this
-- file has run once and then re-runs it. On that first pass the plugin's
-- namespace and its `plugin.<name>` config keys do not exist yet, so
-- unguarded plugin config would error (or, if a plugin failed to build/load,
-- take the whole config down with it).

-- hyprtasking: workspace overview. SUPER+O opens it on the monitor under the
-- cursor; left-drag moves windows between workspaces, right-click switches.
-- The grid is filled with the workspaces bound to that monitor by host.lua
-- (1-5 / 6-10); 1x5 matches that exactly, so the overview never invents extra
-- workspaces for empty slots.
if hl.plugin.hyprtasking then
    hl.config({
        plugin = {
            hyprtasking = {
                layout = "grid",
                gap_size = 10,
                border_size = 2,
                bg_color = 0xff1a1a1a,
                gestures = { enabled = false },
                grid = { rows = 1, cols = 5, layers = 1, loop = false },
            },
        },
    })
    hl.bind(mainMod .. " + O", function() hl.plugin.hyprtasking.toggle("cursor") end)
    -- Escape closes the overview; non_consuming so it still reaches the
    -- focused app when the overview is not open
    hl.bind("escape", function()
        if hl.plugin.hyprtasking.is_active() then
            hl.plugin.hyprtasking.toggle("all")
        end
    end, { non_consuming = true })
end

-- hypr-dynamic-cursors: the cursor tilts with horizontal movement, and
-- shaking it magnifies it (shake to find) -- both are the plugin defaults.
if hl.plugin.dynamic_cursors then
    hl.config({
        plugin = {
            dynamic_cursors = {
                enabled = true,
                mode = "tilt",
                shake = { enabled = true },
            },
        },
    })
end

-- hyprfocus: flashes the newly focused window on keyboard-driven focus
-- changes (mouse focus stays unanimated so follow_mouse does not flicker).
if hl.plugin.hyprfocus then
    hl.config({
        plugin = {
            hyprfocus = {
                keyboard_focus_animation = "flash",
                mouse_focus_animation = "none",
            },
        },
    })
end

-- hypr-darkwindow: SUPER+I toggles colour inversion on the active window,
-- a forced dark mode for apps that only have a light theme. Pressing it again
-- removes the shader.
if hl.plugin.darkwindow then
    hl.config({ plugin = { darkwindow = { load_shaders = "invert" } } })
    hl.bind(mainMod .. " + I", hl.plugin.darkwindow.dsp_shade({ shader = "invert" }))
end

-- hyprbars: title bars with a close and a maximize button; double-click the
-- bar to maximize. Button actions are shell commands, and `hyprctl dispatch`
-- takes Lua since 0.56, hence the hl.dsp strings.
if hl.plugin.hyprbars then
    hl.config({
        plugin = {
            hyprbars = {
                bar_height = 22,
                bar_color = 0xff1a1a1a,
                ["col.text"] = 0xffcccccc,
                bar_text_font = "Berkeley Mono",
                bar_text_size = 10,
                bar_part_of_window = true,
                bar_precedence_over_border = true,
                on_double_click = "hyprctl dispatch 'hl.dsp.window.fullscreen({ mode = \"maximized\" })'",
            },
        },
    })
    hl.plugin.hyprbars.add_button({
        bg_color = "rgb(ff5f57)",
        fg_color = "rgb(1a1a1a)",
        size = 12,
        icon = "",
        action = "hyprctl dispatch 'hl.dsp.window.close()'",
    })
    hl.plugin.hyprbars.add_button({
        bg_color = "rgb(febc2e)",
        fg_color = "rgb(1a1a1a)",
        size = 12,
        icon = "",
        action = "hyprctl dispatch 'hl.dsp.window.fullscreen({ mode = \"maximized\" })'",
    })
end
